server:
  port: 8110
  tomcat:
    max-threads: 10 #修改最大并发量为10

spring:
  profiles:
    active: dev # 环境设置
  application:
    name: service-edu # 服务名
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/academy?serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: xiongyuhang
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #nacos服务地址
    sentinel:
      transport:
        port : 8081
        dashboard: localhost:8080

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

service-oss: # 调用的提供者的名称
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule

ribbon:
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
  ConnectTimeout: 5000
  ReadTimeout: 5000

feign:
  sentinel:
    enabled: true

